---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-watcher.serviceAccountName" . }}
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
rules:
  - apiGroups:
    - ""
    resources:
{{- if .Values.watcher.resources.event }}
    - events
{{- end }}
{{- if .Values.watcher.resources.pod }}
    - pods
{{- end }}
{{- if .Values.watcher.resources.replicationController }}
    - replicationcontrollers
{{- end }}
{{- if .Values.watcher.resources.service }}
    - services
{{- end }}
{{- if .Values.watcher.resources.namespace }}
    - namespaces
{{- end }}
{{- if .Values.watcher.resources.configMap }}
    - configmaps
{{- end }}
{{- if .Values.watcher.resources.node }}
    - nodes
{{- end }}
{{- if .Values.watcher.resources.persistentVolume }}
    - persistentvolumes
{{- end }}
{{- if .Values.watcher.resources.persistentVolumeClaim }}
    - persistentvolumeclaims
{{- end }}
{{- if .Values.watcher.resources.serviceAccount }}
    - serviceaccounts
{{- end }}
{{- if .Values.watcher.resources.secret }}
    - secrets
{{- end }}
{{- if .Values.watcher.resources.endpoints }}
    - endpoints
{{- end }}
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - rbac
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    verbs:
    - get
    - watch
    - list
  - apiGroups: # Required as minimum installation
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - get
    - watch
    - list
{{- if .Values.watcher.resources.job }}
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - get
    - watch
    - list
{{- end }}
{{- if .Values.watcher.resources.ingress }}
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - watch
    - list    
{{- end }}
{{- if .Values.watcher.enableAgentTaskExecution }}
  - apiGroups:
    - ""
    resources:
    - pods
{{- if .Values.watcher.allowReadingPodLogs }}
    - pods/log
{{- end }}
    verbs:
    - "get"
    - "list"
{{- end }}
{{- if .Values.watcher.resources.storageClass }}
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - watch
    - list
{{- end }}
  # Required to validate if enabled CRDs are enabled on cluster
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - watch
    - list
{{- if .Values.watcher.resources.rollout }}
  - apiGroups:
    - argoproj.io
    resources:
    - rollouts
    - rollouts/status
    - rollouts/finalizers
    - analysistemplates
    - clusteranalysistemplates
    verbs:
    - get
    - watch
    - list
{{- end }}
{{- if .Values.watcher.resources.metrics }}
  - apiGroups:
    - metrics.k8s.io
    resources:
    - nodes
    - pods
    verbs:
    - get
    - watch
    - list
{{- end }}
        
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-watcher.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-watcher.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-watcher.serviceAccountName" . }}
    {{- if hasKey .Values "namespace" }}
    namespace: {{ .Values.namespace }}
    {{- end }}
