apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-watcher.name" . }}-secret
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
type: Opaque
data:
  installationId: {{ .Values.apiKey | required "apiKey is a required value!" | b64enc }}
{{- if .Values.kialiApiKey }}
  kialiInstallationId: {{ .Values.kialiApiKey | default "" | b64enc}}
{{- end }}