apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-watcher.name" . }}-secret
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
type: Opaque
data:
  installationId: {{ .Values.watcher.secret.installationId | required ".watcher.secret.installationId is a required value!" }}
  kialiInstallationId: {{ .Values.watcher.secret.kialiInstallationId | default "" }}