apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-watcher.name" . }}-secret
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
type: Opaque
data:
  installationId: {{ .Values.installationId | required "installationId is a required value!" }}
{{- if .Values.kialiInstallationId }}
  kialiInstallationId: {{ .Values.kialiInstallationId | default "" }}
{{- end }}