apiVersion: v2
name: k8s-watcher
description: Watches and send kubernetes resource-related events
type: application
icon: https://raw.githubusercontent.com/komodorio/helm-charts/master/placeholder-logo.png
version: 0.1.6
appVersion: 0.1.0
