apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- logs-reader.cr.yaml
configMapGenerator:
  - behavior: merge
    name: k8s-watcher-config
    files:
      - "komodor-k8s-watcher.yaml"