apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-watcher-config
  namespace: komodor
data:
  komodor-k8s-watcher.yaml: |
    allowReadingPodLogs: true
    collectHistory: true
    controller:
      resync:
        period: "0"
    enableAgentTaskExecution: true
    nameBlacklist:
    - leader
    - election
    namespacesBlacklist:
    - kube-system
    redact: []
    resources:
      rollout: true
      clusterRole: true
      configMap: true
      daemonSet: true
      deployment: true
      endpoints: true
      event: true
      ingress: true
      job: true
      namespace: true
      node: true
      persistentVolume: true
      persistentVolumeClaim: true
      pod: true
      replicaSet: true
      replicationController: true
      secret: false
      service: true
      serviceAccount: true
      statefulSet: true
      storageClass: true
    servers:
      healthCheck: {}
    watchNamespace: all
---

