apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-watcher
  namespace: komodor
  labels:
    helm.sh/chart: k8s-watcher-0.1.6
    app.kubernetes.io/name: k8s-watcher
    app.kubernetes.io/instance: k8s-watcher
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-watcher
      app.kubernetes.io/instance: k8s-watcher
  template:
    metadata:
      annotations:
        checksum/config: 38b5bc7edc02f5c0d13cb36c2ac235782358bbf8f880d9041b1b05804edf89fd
      labels:
        app.kubernetes.io/name: k8s-watcher
        app.kubernetes.io/instance: k8s-watcher
    spec:
      serviceAccountName: k8s-watcher
      containers:
        - name: k8s-watcher
          image: "komodorio/k8s-watcher:latest"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: configuration
              mountPath: /etc/komodor
          env:
            - name: KOMOKW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: k8s-watcher-secret
                  key: apiKey
      volumes:
        - name: configuration
          configMap:
            name: k8s-watcher-config
            items:
              - key: komodor-k8s-watcher.yaml
                path: komodor-k8s-watcher.yaml
