apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-watcher
  namespace: k8s-watcher
  labels:
    helm.sh/chart: k8s-watcher-0.1.4
    app.kubernetes.io/name: k8s-watcher
    app.kubernetes.io/instance: k8s-watcher
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
---
